library(lme4)
library(lmerTest)
library(LMERConvenienceFunctions)
library(multcomp)

mJunGc <- lmer(log(gc) ~ spp*leafAge + (1|ID) + (1|fround), data=jun)
summary(mJunGc)
anova(mJunGc)
mcp.fnc(mJunGc)
summary(glht(mJunGc, linfct=mcp(spp="Tukey")))
mJunA <- lmer(Photo ~ spp*leafAge + (1|ID) + (1|fround), data=jun)
summary(mJunA)
anova(mJunA)
mcp.fnc(mJunA)
summary(glht(mJunA, linfct=mcp(spp="Tukey")))

mAugGc <- lmer(log(gc) ~ spp*treatment + (1|ID) + (1|fround), data=aug)
summary(mAugGc)
anova(mAugGc)
mcp.fnc(mAugGc)
summary(glht(mAugGc, linfct=mcp(spp="Tukey")))
mAugA <- lmer(Photo ~ spp*treatment + (1|ID) + (1|fround), data=aug)
summary(mAugA)
anova(mAugA)
mcp.fnc(mAugA)
summary(glht(mAugA, linfct=mcp(spp="Tukey")))
