windows(12,8)
par(mfrow=c(2,2))
kk <- max(gasex$gc)
pp <- max(gasex$MESindex, na.rm=T)
rr <- max(gasex$CAPindex, na.rm=T)
with(subset(jun, spp== 'PTE' & leafAge=='mature'), plot(gc~MESindex, pch=15, col='blue', ylim=c(0,kk), 
                                                        xlim=c(-0.001,pp), ylab='gc (mmol/m2/s)', xlab='MES index'))
with(subset(jun, spp== 'PTE' & leafAge=='young'), points(gc~MESindex, pch=17, col='blue'))
with(subset(jun, spp== 'BET' & leafAge=='young'), points(gc~MESindex, pch=17, col='red'))
with(subset(jun, spp== 'BET' & leafAge=='mature'), points(gc~MESindex, pch=15, col='red'))
with(subset(jun, spp== 'QUE' & leafAge=='mature'), points(gc~MESindex, pch=15, col='magenta'))
with(subset(jun, spp== 'QUE' & leafAge=='young'), points(gc~MESindex, pch=17, col='magenta'))
with(subset(jun, spp== 'EUC' & leafAge=='young'), points(gc~MESindex, pch=17, col='cyan'))
with(subset(jun, spp== 'EUC' & leafAge=='mature'), points(gc~MESindex, pch=15, col='cyan'))
with(subset(jun, spp== 'PIN' & leafAge=='mature'), points(gc~MESindex, pch=15, col='forestgreen'))
with(subset(jun, spp== 'PIN' & leafAge=='young'), points(gc~MESindex, pch=17, col='forestgreen'))
with(subset(jun, spp== 'MOL' & leafAge=='young'), points(gc~MESindex, pch=17, col='black'))
with(subset(jun, spp== 'MOL' & leafAge=='mature'), points(gc~MESindex, pch=15, col='black'))
with(subset(jun, spp== 'ZEA' & leafAge=='young'), points(gc~MESindex, pch=17, col='darkgrey'))
with(subset(jun, spp== 'ZEA' & leafAge=='mature'), points(gc~MESindex, pch=15, col='darkgrey'))
legend('topright', pch=c(17,15), legend=c('developing','mature'), bty='n')
aug2 <- subset(aug, leafAge=='mature')
aug2$wt <- as.factor(ifelse(aug2$treatment=='control', 'WW', 'WS'))
with(subset(aug2, spp== 'PTE' & wt=='WW'), plot(gc~MESindex, pch=19, col='blue', ylim=c(0,kk), 
                                                        xlim=c(-0.001,rr), ylab='gc (mmol/m2/s)', xlab='MES index'))
with(subset(aug2, spp== 'PTE' & wt=='WS'), points(gc~MESindex, pch=18, col='blue'))
with(subset(aug2, spp== 'BET' & wt=='WS'), points(gc~MESindex, pch=18, col='red'))
with(subset(aug2, spp== 'BET' & wt=='WW'), points(gc~MESindex, pch=19, col='red'))
with(subset(aug2, spp== 'QUE' & wt=='WW'), points(gc~MESindex, pch=19, col='magenta'))
with(subset(aug2, spp== 'QUE' & wt=='WS'), points(gc~MESindex, pch=18, col='magenta'))
with(subset(aug2, spp== 'EUC' & wt=='WS'), points(gc~MESindex, pch=18, col='cyan'))
with(subset(aug2, spp== 'EUC' & wt=='WW'), points(gc~MESindex, pch=19, col='cyan'))
with(subset(aug2, spp== 'PIN' & wt=='WW'), points(gc~MESindex, pch=19, col='forestgreen'))
with(subset(aug2, spp== 'PIN' & wt=='WS'), points(gc~MESindex, pch=18, col='forestgreen'))
with(subset(aug2, spp== 'MOL' & wt=='WS'), points(gc~MESindex, pch=18, col='black'))
with(subset(aug2, spp== 'MOL' & wt=='WW'), points(gc~MESindex, pch=19, col='black'))
with(subset(aug2, spp== 'ZEA' & wt=='WS'), points(gc~MESindex, pch=18, col='darkgrey'))
with(subset(aug2, spp== 'ZEA' & wt=='WW'), points(gc~MESindex, pch=19, col='darkgrey'))
legend('topright', pch=c(19,18), legend=c('WW','WS'), bty='n')
with(subset(jun, spp== 'PTE' & leafAge=='mature'), plot(gc~CAPindex, pch=15, col='blue', ylim=c(0,kk), 
                                                        xlim=c(-0.001,rr), ylab='gc (mmol/m2/s)', xlab='CAP index'))
with(subset(jun, spp== 'PTE' & leafAge=='young'), points(gc~CAPindex, pch=17, col='blue'))
with(subset(jun, spp== 'BET' & leafAge=='young'), points(gc~CAPindex, pch=17, col='red'))
with(subset(jun, spp== 'BET' & leafAge=='mature'), points(gc~CAPindex, pch=15, col='red'))
with(subset(jun, spp== 'QUE' & leafAge=='mature'), points(gc~CAPindex, pch=15, col='magenta'))
with(subset(jun, spp== 'QUE' & leafAge=='young'), points(gc~CAPindex, pch=17, col='magenta'))
with(subset(jun, spp== 'EUC' & leafAge=='young'), points(gc~CAPindex, pch=17, col='cyan'))
with(subset(jun, spp== 'EUC' & leafAge=='mature'), points(gc~CAPindex, pch=15, col='cyan'))
with(subset(jun, spp== 'PIN' & leafAge=='mature'), points(gc~CAPindex, pch=15, col='forestgreen'))
with(subset(jun, spp== 'PIN' & leafAge=='young'), points(gc~CAPindex, pch=17, col='forestgreen'))
with(subset(jun, spp== 'MOL' & leafAge=='young'), points(gc~CAPindex, pch=17, col='black'))
with(subset(jun, spp== 'MOL' & leafAge=='mature'), points(gc~CAPindex, pch=15, col='black'))
with(subset(jun, spp== 'ZEA' & leafAge=='young'), points(gc~CAPindex, pch=17, col='darkgrey'))
with(subset(jun, spp== 'ZEA' & leafAge=='mature'), points(gc~CAPindex, pch=15, col='darkgrey'))

aug2 <- subset(aug, leafAge=='mature')
aug2$wt <- as.factor(ifelse(aug2$treatment=='control', 'WW', 'WS'))
with(subset(aug2, spp== 'PTE' & wt=='WW'), plot(gc~CAPindex, pch=19, col='blue', ylim=c(0,kk), 
                                                xlim=c(-0.001,rr), ylab='gc (mmol/m2/s)', xlab='CAP index'))
with(subset(aug2, spp== 'PTE' & wt=='WS'), points(gc~CAPindex, pch=18, col='blue'))
with(subset(aug2, spp== 'BET' & wt=='WS'), points(gc~CAPindex, pch=18, col='red'))
with(subset(aug2, spp== 'BET' & wt=='WW'), points(gc~CAPindex, pch=19, col='red'))
with(subset(aug2, spp== 'QUE' & wt=='WW'), points(gc~CAPindex, pch=19, col='magenta'))
with(subset(aug2, spp== 'QUE' & wt=='WS'), points(gc~CAPindex, pch=18, col='magenta'))
with(subset(aug2, spp== 'EUC' & wt=='WS'), points(gc~CAPindex, pch=18, col='cyan'))
with(subset(aug2, spp== 'EUC' & wt=='WW'), points(gc~CAPindex, pch=19, col='cyan'))
with(subset(aug2, spp== 'PIN' & wt=='WW'), points(gc~CAPindex, pch=19, col='forestgreen'))
with(subset(aug2, spp== 'PIN' & wt=='WS'), points(gc~CAPindex, pch=18, col='forestgreen'))
with(subset(aug2, spp== 'MOL' & wt=='WS'), points(gc~CAPindex, pch=18, col='black'))
with(subset(aug2, spp== 'MOL' & wt=='WW'), points(gc~CAPindex, pch=19, col='black'))
with(subset(aug2, spp== 'ZEA' & wt=='WS'), points(gc~CAPindex, pch=18, col='darkgrey'))
with(subset(aug2, spp== 'ZEA' & wt=='WW'), points(gc~CAPindex, pch=19, col='darkgrey'))
legend('topright', pch=19, legend=c('PTE','BET','QUE','EUC','PIN','MOL','ZEA'),
       col=c('blue', 'red','magenta','cyan','forestgreen','black','darkgrey'), bty='n')
